services:
  test_nikki:
    build:
      context: .
    depends_on:
      - test_db
    env_file:
      - ./.env.docker.test.local
    ports:
      - 3000:3000

  test_db:
    image: "postgres:15.6-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-local-db
    ports:
      - "5432:5432"
